/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.jimenezhidalgo.uni.programacion.poker2.gui;

import es.jimenezhidalgo.uni.programacion.poker2.CasaApuestas;
import es.jimenezhidalgo.uni.programacion.poker2.JugadorRegistrado;
import es.jimenezhidalgo.uni.programacion.poker2.exceptions.JugadorException;
import es.jimenezhidalgo.uni.programacion.poker2.utils.DateUtils;
import es.jimenezhidalgo.uni.programacion.poker2.utils.NIFHelper;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author jesus.jimenez
 */
public class VentanaRegistroJugadorRegistrado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroJugadorRegistrado
     */
    public VentanaRegistroJugadorRegistrado() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        fechaNacimientoJSpinner.setEditor(new JSpinner.DateEditor(fechaNacimientoJSpinner , "dd/MM/yyyy"));
        fechaRegistroJSpinner.setEditor(new JSpinner.DateEditor(fechaRegistroJSpinner , "dd/MM/yyyy"));
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                new VentanaPrincipal();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registroJLabel = new javax.swing.JLabel();
        salirJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nifJTextField = new javax.swing.JTextField();
        nombreJLabel = new javax.swing.JLabel();
        nombreJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellidosJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaNacimientoJSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        saldoJSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cuentaBancariaJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaRegistroJSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        contraseniaJPasswordField = new javax.swing.JPasswordField();
        registroJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jPanel2.setBackground(new java.awt.Color(33, 150, 243));

        registroJLabel.setBackground(new java.awt.Color(250, 250, 250));
        registroJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        registroJLabel.setForeground(new java.awt.Color(250, 250, 250));
        registroJLabel.setText("REGISTRO");

        salirJButton.setText("Salir");
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(registroJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirJButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirJButton)
                    .addComponent(registroJLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText(" NIF");

        nifJTextField.setToolTipText("Introduzca su nif");
        nifJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nifJTextFieldActionPerformed(evt);
            }
        });

        nombreJLabel.setText(" Nombre");

        nombreJTextField.setToolTipText("Introduzca su nombre");

        jLabel2.setText(" Apellidos");

        apellidosJTextField.setToolTipText("Introduzca sus apellidos");

        jLabel3.setText(" Fecha de nacimiento");

        fechaNacimientoJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(68400000L), null, null, java.util.Calendar.DAY_OF_MONTH));

        jLabel4.setText(" Saldo");

        saldoJSpinner.setModel(new javax.swing.SpinnerNumberModel(50.0d, null, null, 0.01d));

        jLabel5.setText(" Cuenta bancaria");

        cuentaBancariaJTextField.setToolTipText("Introduzca su cuenta bancaria");

        jLabel6.setText(" FechaRegistro");

        fechaRegistroJSpinner.setModel(new javax.swing.SpinnerDateModel());

        jLabel7.setText(" Contraseña");

        contraseniaJPasswordField.setToolTipText("Introfuzca su contraseña");
        contraseniaJPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaJPasswordFieldActionPerformed(evt);
            }
        });

        registroJButton.setText("Registrarme!");
        registroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroJButtonActionPerformed(evt);
            }
        });

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nifJTextField)
                    .addComponent(contraseniaJPasswordField)
                    .addComponent(nombreJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apellidosJTextField)
                    .addComponent(fechaNacimientoJSpinner)
                    .addComponent(saldoJSpinner)
                    .addComponent(cuentaBancariaJTextField)
                    .addComponent(fechaRegistroJSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(nombreJLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addComponent(registroJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancelarJButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nifJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseniaJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaNacimientoJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentaBancariaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaRegistroJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registroJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarJButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseniaJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaJPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaJPasswordFieldActionPerformed

    private void nifJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nifJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nifJTextFieldActionPerformed

    private void registroJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroJButtonActionPerformed
        String nif = nifJTextField.getText();
        String contrasenia = contraseniaJPasswordField.getText();
        String nombre = nombreJTextField.getText();
        String apellidos = apellidosJTextField.getText();
        Date fechaNacimiento = (Date) fechaNacimientoJSpinner.getValue();
        double saldo = (double) saldoJSpinner.getValue();
        String cuentaBancaria = cuentaBancariaJTextField.getText();
        Date fechaRegistro = (Date) fechaRegistroJSpinner.getValue();
        
        String mensajeError = "";
        
        try{
            if(nif.equals("")) {
                mensajeError += "Debe de introducir su NIF\n";
            } else {
                NIFHelper.comprobarLetraNif(nif);
            }
        } catch (JugadorException e){
            mensajeError += "El NIF introducido no es válido\n";
        }
        
        if(contraseniaJPasswordField.getText().equals("")){
            mensajeError += "Debe de introducir su contraseña\n";
        }
        
        if(nombreJTextField.getText().equals("")){
            mensajeError += "Debe de introducir su nombre\n";
        }
        
        if(apellidosJTextField.getText().equals("")){
            mensajeError += "Debe de introducir sus apellidos\n";
        }
        
        if(fechaNacimiento.after(new Date())){
            mensajeError += "La fecha de nacimiento no puede ser posterior a hoy\n";
        }
        
        if(cuentaBancariaJTextField.getText().equals("")){
            mensajeError += "Debe de introducir su cuenta bancaria\n";
        }
        
        if(fechaRegistro.after(new Date())){
            mensajeError += "La fecha de registro no puede ser posterior a hoy\n";
        }
        
        if(saldo <= 0) {
            mensajeError += "El saldo debe ser mayor que 0\n";
        }
        
        if(mensajeError.equals("")){
            try {
                nif = nif.substring(0, 8) + nif.substring(8).toUpperCase();
                CasaApuestas.altaJugador(new JugadorRegistrado(nif, nombre, apellidos, saldo, fechaNacimiento, cuentaBancaria, contrasenia, fechaRegistro));
            } catch (JugadorException e) {
                mensajeError += e.getMessage();
            }
        }
        
        if(!mensajeError.equals("")){
            JOptionPane.showMessageDialog(this, "Se han producido los siguientes errores:\n\n" + mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Se ha registrado correctamente, ahora inicie sesión para poder jugar." + mensajeError, "Registro correcto", JOptionPane.INFORMATION_MESSAGE);
            new VentanaPrincipal();
            dispose();
        }
        
    }//GEN-LAST:event_registroJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JPasswordField contraseniaJPasswordField;
    private javax.swing.JTextField cuentaBancariaJTextField;
    private javax.swing.JSpinner fechaNacimientoJSpinner;
    private javax.swing.JSpinner fechaRegistroJSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nifJTextField;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JTextField nombreJTextField;
    private javax.swing.JButton registroJButton;
    private javax.swing.JLabel registroJLabel;
    private javax.swing.JSpinner saldoJSpinner;
    private javax.swing.JButton salirJButton;
    // End of variables declaration//GEN-END:variables
}
