/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.jimenezhidalgo.uni.programacion.poker2.gui;

import es.jimenezhidalgo.uni.programacion.poker2.CasaApuestas;
import es.jimenezhidalgo.uni.programacion.poker2.JugadorRegistrado;
import es.jimenezhidalgo.uni.programacion.poker2.Main;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus.jimenez
 */
public class VentanaListaJugadores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListaJugadores
     */
    public VentanaListaJugadores() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                new VentanaPrincipal();
            }
        });
        
        DefaultListModel modeloNif = new DefaultListModel();
        DefaultListModel modeloNombre = new DefaultListModel();
        DefaultListModel modeloSaldo = new DefaultListModel();
        
        List<JugadorRegistrado> jugadoresRegistrados = new ArrayList<>(CasaApuestas.sJugadoresRegistrados.values());
        
        for(JugadorRegistrado jugadorRegistrado : jugadoresRegistrados){
            modeloNif.addElement(jugadorRegistrado.getNif());
            modeloNombre.addElement(jugadorRegistrado.getNombre() + " " + jugadorRegistrado.getApellidos());
            modeloSaldo.addElement(jugadorRegistrado.getSaldo());
            nifJComboBox.addItem(jugadorRegistrado.getNif());
            nifJComboBox2.addItem(jugadorRegistrado.getNif());
            nifJComboBox1.addItem(jugadorRegistrado.getNif());
        }
        
        nifJList.setModel(modeloNif);
        nombreJList.setModel(modeloNombre);
        saldoJList.setModel(modeloSaldo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registroJLabel = new javax.swing.JLabel();
        salirJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nifJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        nombreJList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        saldoJList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        darDeBajaJButton = new javax.swing.JButton();
        nifJComboBox = new javax.swing.JComboBox<>();
        nifJComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cantidadAIngresarJSpinner = new javax.swing.JSpinner();
        ingresarDineroJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nifJComboBox1 = new javax.swing.JComboBox<>();
        retirarFondosJButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jPanel2.setBackground(new java.awt.Color(55, 71, 79));

        registroJLabel.setBackground(new java.awt.Color(250, 250, 250));
        registroJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        registroJLabel.setForeground(new java.awt.Color(250, 250, 250));
        registroJLabel.setText("JUGADORES REGISTRADOS");

        salirJButton.setText("Salir");
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(registroJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirJButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirJButton)
                    .addComponent(registroJLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(nifJList);

        jScrollPane2.setViewportView(nombreJList);

        jScrollPane3.setViewportView(saldoJList);

        jLabel2.setText(" NIF");

        jLabel3.setText(" Nombre y apellidos");

        jLabel4.setText(" Saldo");

        jLabel7.setText(" Dar de baja jugador con NIF: ");

        darDeBajaJButton.setForeground(new java.awt.Color(244, 67, 54));
        darDeBajaJButton.setText("Dar de baja");
        darDeBajaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeBajaJButtonActionPerformed(evt);
            }
        });

        nifJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un NIF" }));

        nifJComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un NIF" }));

        jLabel8.setText("Ingresar dinero a: ");

        cantidadAIngresarJSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.05d));

        ingresarDineroJButton1.setForeground(new java.awt.Color(33, 33, 33));
        ingresarDineroJButton1.setText("Ingresar");
        ingresarDineroJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarDineroJButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("RetirarFondos :");

        nifJComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un NIF" }));

        retirarFondosJButton.setForeground(new java.awt.Color(33, 33, 33));
        retirarFondosJButton.setText("Retirar beneficios");
        retirarFondosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarFondosJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 53, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nifJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nifJComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cantidadAIngresarJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nifJComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(darDeBajaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresarDineroJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retirarFondosJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(nifJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(darDeBajaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(nifJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantidadAIngresarJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ingresarDineroJButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(nifJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(retirarFondosJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed

    private void darDeBajaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeBajaJButtonActionPerformed
       
        String nif = "";
        
        if((nif = (String) nifJComboBox.getSelectedItem()).equals("Seleccione un NIF")){
           JOptionPane.showMessageDialog(this, "Seleccione un NIF para dar de baja\n", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        if( CasaApuestas.bajaJugador(nif) == null){
            JOptionPane.showMessageDialog(this, "No se ha podido dar de baja al jugador\n", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Se ha dado de baja al jugador con NIF " + nif + " con éxito", "Dado de baja con éxito", JOptionPane.INFORMATION_MESSAGE);
            new VentanaListaJugadores();
            dispose();
        }
    }//GEN-LAST:event_darDeBajaJButtonActionPerformed

    private void ingresarDineroJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarDineroJButton1ActionPerformed
        String nif = "";
        
        if((nif = (String) nifJComboBox2.getSelectedItem()).equals("Seleccione un NIF")){
           JOptionPane.showMessageDialog(this, "Seleccione un NIF para dar de baja\n", "Error", JOptionPane.INFORMATION_MESSAGE);
           return;
        }
        
        if((double) cantidadAIngresarJSpinner.getValue() <= 0) {
           JOptionPane.showMessageDialog(this, "Debe de ingresar una cantidad mayor que 0\n", "Error", JOptionPane.INFORMATION_MESSAGE);
           return;
        }
        
        Main.sJugador.aumentarSaldo((double) cantidadAIngresarJSpinner.getValue());
        new VentanaListaJugadores();
        dispose();
    }//GEN-LAST:event_ingresarDineroJButton1ActionPerformed

    private void retirarFondosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarFondosJButtonActionPerformed
        String nif = "";
        
        if((nif = (String) nifJComboBox1.getSelectedItem()).equals("Seleccione un NIF")){
           JOptionPane.showMessageDialog(this, "Seleccione un NIF para dar de baja\n", "Error", JOptionPane.INFORMATION_MESSAGE);
           return;
        }
        
        Main.sJugador.retirarBeneficios();
        new VentanaListaJugadores();
        dispose();
    }//GEN-LAST:event_retirarFondosJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidadAIngresarJSpinner;
    private javax.swing.JButton darDeBajaJButton;
    private javax.swing.JButton ingresarDineroJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> nifJComboBox;
    private javax.swing.JComboBox<String> nifJComboBox1;
    private javax.swing.JComboBox<String> nifJComboBox2;
    private javax.swing.JList<String> nifJList;
    private javax.swing.JList<String> nombreJList;
    private javax.swing.JLabel registroJLabel;
    private javax.swing.JButton retirarFondosJButton;
    private javax.swing.JList<Double> saldoJList;
    private javax.swing.JButton salirJButton;
    // End of variables declaration//GEN-END:variables
}
