/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.jimenezhidalgo.uni.programacion.poker2.gui;

import es.jimenezhidalgo.uni.programacion.poker2.Apuesta;
import es.jimenezhidalgo.uni.programacion.poker2.Baraja;
import es.jimenezhidalgo.uni.programacion.poker2.Carta;
import es.jimenezhidalgo.uni.programacion.poker2.Main;
import es.jimenezhidalgo.uni.programacion.poker2.utils.PremiosUtils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author jesus.jimenez
 */
public class VentanaApuesta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaApuesta
     */
    public VentanaApuesta() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                new VentanaPrincipal();
            }
        });
        
        nombreJLabel.setText(Main.sJugador.getNombre() + " " + Main.sJugador.getApellidos());
        nifJLabel.setText(Main.sJugador.getNif());
        saldoJLabel.setText(Double.toString(Main.sJugador.getSaldo()));
        apuestaJLabel.setText(Double.toString(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registroJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saldoJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabel7 = new javax.swing.JLabel();
        nifJLabel = new javax.swing.JLabel();
        nombreJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apuestaJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantidadApostadaJTextField = new javax.swing.JTextField();
        apostarJButton = new javax.swing.JButton();
        salirJButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        carta2JLabel = new javax.swing.JLabel();
        carta1JLabel = new javax.swing.JLabel();
        carta5JLabel = new javax.swing.JLabel();
        carta3JLabel = new javax.swing.JLabel();
        carta4JLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jPanel2.setBackground(new java.awt.Color(76, 175, 80));

        registroJLabel.setBackground(new java.awt.Color(250, 250, 250));
        registroJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        registroJLabel.setForeground(new java.awt.Color(250, 250, 250));
        registroJLabel.setText("MESA DE JUEGO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(registroJLabel)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(registroJLabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText("Saldo:");

        jLabel2.setText("Jugador:");

        JLabel7.setText("NIF:");

        jLabel4.setText("Última apuesta:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nifJLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldoJLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apuestaJLabel)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel7)
                    .addComponent(nifJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saldoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apuestaJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Nueva apuesta: ");

        apostarJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        apostarJButton.setForeground(new java.awt.Color(76, 175, 80));
        apostarJButton.setText("Apostar");
        apostarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarJButtonActionPerformed(evt);
            }
        });

        salirJButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        salirJButton.setForeground(new java.awt.Color(244, 67, 54));
        salirJButton.setText("Terminar");
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(27, 94, 32));

        carta2JLabel.setBackground(new java.awt.Color(255, 255, 255));
        carta2JLabel.setPreferredSize(new java.awt.Dimension(100, 139));
        carta2JLabel.setSize(new java.awt.Dimension(100, 139));

        carta1JLabel.setBackground(new java.awt.Color(255, 255, 255));
        carta1JLabel.setPreferredSize(new java.awt.Dimension(100, 139));
        carta1JLabel.setSize(new java.awt.Dimension(100, 139));

        carta5JLabel.setBackground(new java.awt.Color(255, 255, 255));
        carta5JLabel.setSize(new java.awt.Dimension(100, 139));

        carta3JLabel.setBackground(new java.awt.Color(255, 255, 255));
        carta3JLabel.setSize(new java.awt.Dimension(100, 139));

        carta4JLabel.setBackground(new java.awt.Color(255, 255, 255));
        carta4JLabel.setSize(new java.awt.Dimension(100, 139));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carta1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta3JLabel)
                .addGap(18, 18, 18)
                .addComponent(carta4JLabel)
                .addGap(18, 18, 18)
                .addComponent(carta5JLabel)
                .addGap(207, 207, 207))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carta4JLabel)
                    .addComponent(carta5JLabel)
                    .addComponent(carta3JLabel)
                    .addComponent(carta2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadApostadaJTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(apostarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salirJButton)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cantidadApostadaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apostarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salirJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apostarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarJButtonActionPerformed
        double cantidadApostada = 0;
        ArrayList<Carta> mano = new ArrayList<>();
        
        if(Main.sJugador.getSaldo() == 0){
            JOptionPane.showMessageDialog(this, "Se ha quedado sin saldo, ingrese más dinero para continuar", "Error", JOptionPane.ERROR_MESSAGE);
            new VentanaPrincipal();
            dispose();
            return;
        }
        
        if(cantidadApostadaJTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe indicar primero cuánto desea apostar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                cantidadApostada = Double.parseDouble(cantidadApostadaJTextField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Debe introducir un número mayor que 0 (51.45 por ejemplo)", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(cantidadApostada <= 0 || cantidadApostada > Main.sJugador.getSaldo()) {
                JOptionPane.showMessageDialog(this, "Debe hacer una apuesta superior a 0€ e inferior a su saldo", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                try {
                    mano = Baraja.crearMano();
                    Main.sApuesta = new Apuesta(Main.sJugador, mano, cantidadApostada);
                    Main.sJugador.apuestaDinero(cantidadApostada);
                } catch (Carta.CartaExcepcion e) {
                    JOptionPane.showMessageDialog(this, "No se ha podido crear la apuesta por un error desconocido", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                ImageIcon carta1 = new ImageIcon("src/main/resources/cartas_espaniolas/" + mano.get(0).getCartaInt() + ".jpg");
                carta1JLabel.setIcon(carta1);
                ImageIcon carta2 = new ImageIcon("src/main/resources/cartas_espaniolas/" + mano.get(1).getCartaInt() + ".jpg");
                carta2JLabel.setIcon(carta2);
                ImageIcon carta3 = new ImageIcon("src/main/resources/cartas_espaniolas/" + mano.get(2).getCartaInt() + ".jpg");
                carta3JLabel.setIcon(carta3);
                ImageIcon carta4 = new ImageIcon("src/main/resources/cartas_espaniolas/" + mano.get(3).getCartaInt() + ".jpg");
                carta4JLabel.setIcon(carta4);
                ImageIcon carta5 = new ImageIcon("src/main/resources/cartas_espaniolas/" + mano.get(4).getCartaInt() + ".jpg");
                carta5JLabel.setIcon(carta5);
                
                Apuesta.Premio premio = Main.sApuesta.verPremio();
                
                if(premio.getCombinacion() == -1) {
                    JOptionPane.showMessageDialog(this, "Vaya... has perdido");
                } else if (premio.getCombinacion() == 1 ){
                    JOptionPane.showMessageDialog(this, "Enhorabuena! Tienes pareja y has recuperado lo apostado");
                    Main.sJugador.ganaDineroApuesta(premio.getPremioEconomico());
                } else {
                    JOptionPane.showMessageDialog(this, "Enhorabuena! Tienes " + PremiosUtils.COMBINACIONES[premio.getCombinacion() - 1] + " y has ganado " + (premio.getPremioEconomico() - cantidadApostada) + "€");
                    Main.sJugador.ganaDineroApuesta(premio.getPremioEconomico());
                }
                
                saldoJLabel.setText(Double.toString(Main.sJugador.getSaldo()));
                apuestaJLabel.setText(Double.toString(cantidadApostada));
            }
        }
    }//GEN-LAST:event_apostarJButtonActionPerformed

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel7;
    private javax.swing.JButton apostarJButton;
    private javax.swing.JLabel apuestaJLabel;
    private javax.swing.JTextField cantidadApostadaJTextField;
    private javax.swing.JLabel carta1JLabel;
    private javax.swing.JLabel carta2JLabel;
    private javax.swing.JLabel carta3JLabel;
    private javax.swing.JLabel carta4JLabel;
    private javax.swing.JLabel carta5JLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nifJLabel;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JLabel registroJLabel;
    private javax.swing.JLabel saldoJLabel;
    private javax.swing.JButton salirJButton;
    // End of variables declaration//GEN-END:variables
}
